// Writes api/<same path>.js for every engine handler: register the layer,
// then re-export the engine's handler. Vercel deploys api/ from this repo,
// so each engine endpoint needs a wrapper here.
import { readdirSync, statSync, mkdirSync, writeFileSync, rmSync } from "node:fs";
import { join, relative, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = fileURLToPath(new URL("..", import.meta.url));
const ENGINE_API = join(ROOT, "vendor", "shortlist", "api");
const OUT = join(ROOT, "api");

const files = [];
(function walk(dir) {
  for (const f of readdirSync(dir)) {
    const p = join(dir, f);
    if (statSync(p).isDirectory()) walk(p); else if (f.endsWith(".js")) files.push(relative(ENGINE_API, p));
  }
})(ENGINE_API);

rmSync(OUT, { recursive: true, force: true });
for (const f of files) {
  const out = join(OUT, f);
  mkdirSync(dirname(out), { recursive: true });
  const up = relative(dirname(out), ROOT).split("\\").join("/") || ".";
  writeFileSync(out, `// Generated by scripts/wrap-api.mjs: the engine's handler, with this layer registered.\nimport "${up}/layer.js";\nexport * from "${up}/vendor/shortlist/api/${f.split("\\").join("/")}";\n`);
}
console.log(`Wrapped ${files.length} engine endpoints in api/.`);
